// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDXnGTeJ8mMj-g_3WiggY6OZOTuw65NyE',
    appId: '1:568410602920:web:24cdfffaa711f0511c319d',
    messagingSenderId: '568410602920',
    projectId: 'juice-code-test',
    authDomain: 'juice-code-test.firebaseapp.com',
    storageBucket: 'juice-code-test.appspot.com',
    measurementId: 'G-8C350Y130B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDws2QWCUIylShh1Wy-Tyu8yJqaHCaXFrk',
    appId: '1:568410602920:android:732ff19ba32fb9151c319d',
    messagingSenderId: '568410602920',
    projectId: 'juice-code-test',
    storageBucket: 'juice-code-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANW9Jv5ahYRGKO2ob5JdX2ZpWPGP6ntH0',
    appId: '1:568410602920:ios:9b50e237fb36250d1c319d',
    messagingSenderId: '568410602920',
    projectId: 'juice-code-test',
    storageBucket: 'juice-code-test.appspot.com',
    iosBundleId: 'com.pyaesone.juiceCodeTest',
  );
}
